### ISSUE TITLE
Doesn't like to open already-modified ROMs

### ISSUE THREAD

**Issue by BlueFinch3000** [mchlnix/SMB3-Foundry#26]
For some reason, the program doesn't like when i try to open a rom that is not stock, vanilla SMB3. It has opened some modified roms before, but most of the time, it will simply close the program after not finding something it was looking for. It allows me to try to open the rom, of course, but upon clicking 'open', it will shut down.

Edit 1:
I opened a stock rom, then tried to open a 'troublesome' rom and i saw this in the command prompt:
"IndexError: list index out of range"

Edit 2:
It seems to be fine opening levels up until it reaches one whose stock boundaries are no longer intact (where there is overflow of data or enemies, maybe?).

**Comment by mchlnix** [comment]
When those errors occur saving the information from 'Traceback: ...' until the end is helpful, so that I can see where the error occurs. And this might have something to do with the editor assuming the stock level addresses as you said. Detecting/Reading the levels from the ROM could be a way to fix this, but takes a decent amount of work.

Should be doable, though.

**Comment by mchlnix** [comment]
Would also be good to add the offending rom here, so I can test it as well.

**Comment by mchlnix** [comment]
Seems like older Editors ended the enemy data section only with a 0xFF, instead of 0xFF00 or 0xFF01 as I saw everywhere in the stock rom, which is why the editor didn't recognized it as the end and just read garbage until the rom was over.

Fixing this made the rom load normally.
