### ISSUE TITLE
In-level pointers

### ISSUE THREAD

**Issue by BlueFinch3000** [mchlnix/SMB3-Foundry#30]
Image 1 - Header Dialog
Image 2 - Pointers Dialog

The 'next area' pointer in Image 1 is for telling the level what to load next when player goes through a warp pipe or a door.
The 'pointer properties' in image 2 is to tell the following:
Entrance Horizontal: WHERE the door or pipe is in the level (70-7F meaning 'somewhere, anywhere, between x position 70 through 7F).
Exit Horizontal: WHERE exactly the player is spit out into the 'next area' (horizontally)
Exit Vertical: WHERE (from a specific set of Y locations only, for some reason) the player is spit out vertically in the next area.
Exit Action: HOW does the player appear in the next area. (if the player enters a pipe, he must come out of a pipe: either up, down, left or right; that doesn't matter. he cannot enter a pipe then come out of a door though)
![BCB5D55A-44FD-4E5D-9C4A-4C1B9BA96ABE](https://user-images.githubusercontent.com/50643584/59151811-8c9cc800-8a07-11e9-86df-265a13ca92c9.jpeg)

**Comment by mchlnix** [comment]
It seems like, based on the Entrance-Horizontal input, that there can only be one entrance per screen, but it can be at any vertical position. In Vertical levels this is probably switched, since the screens are aligned vertically instead of horizontally.

Basically it should be possible to add a right-click menu item "Add/Change Pointer" where you want to have it and the editor filling the information in, then displaying the graphic.

If the position of the pointer inside the object data doesn't matter it is possible to have a pointer list for the level outside of the objects themselves and read/write them separately.

That would make Pointers a special kind of object, which I don't really like, but rendering it like a normal object also makes no sense.

**Comment by mchlnix** [comment]
Changing the next area pointers is already #11, so this is basically done.
