### ISSUE TITLE
Would like to redo a poll for the way foundry displays items inside blocks.

### ISSUE THREAD

**Issue by Doublebass1985** [mchlnix/SMB3-Foundry#81]
Personally I favor the way Workshop displays the items inside objects by having the leaf, flower, or star, whatever it may be inside the actual box where as in foundry you guys have it ontop of the box and this results in the items blocking or covering up objects that may be ontop of them.  Basically it just will look a lot cleaner having this fixed to the way Workshop has these bricks and blocks displayed.

**Comment by TheJoeSmo** [comment]
Personally, I believe a setting to allow either of the two methods would be preferred.  People will go back and forth on the issue.  With a setting you pick whatever you like best and move on.

**Comment by mchlnix** [comment]
There is also a setting to disable those hints in the View menu.

**Comment by TheJoeSmo** [comment]
Yeah, we will need to rely on settings in the future.  How we should go about adding these settings should be a matter of debate though.  I'm against making a poll as it will simply lead to a similar issue down the line.  And if we were to make a poll, where should it go and what should the options be?

**Comment by WildLicorice** [comment]
I'm very new, so take this opinion for what it's worth, but I don't mind either way. My issue is more selecting the correct brink with the correct item from the Objects list. I wish they icon would have the item over the brink so I don't have to hover for the text pop up. Although this would be minor because I know you can also select the brick from the Object Dropdown so I guess it would come down to workflow.

**Comment by mchlnix** [comment]
I added the item overlays to the object toolbar. The other stuff can be toggled, if necessary, so maybe later.
