### ISSUE TITLE
Incorrect drawing of objects using BG palette on blank space objects

### ISSUE THREAD

**Issue by Dragonsbrethren** [mchlnix/SMB3-Foundry#90]
SMB3 Foundry does not properly render object generators that use empty space tiles using the BG palette color. For example:

- **Plains Object $00, $A2 (Gap)** - Correctly draws the right and left ground tiles, but the middle gap is rendered transparent and shows whatever generator is behind it.
- **Desert Object $03, $C7 (Horizontal Plain Background B)** - Simply rendered transparent, any underlying objects are drawn as normal. This is notably used for the pipe mazes in 2-1 and 7-9, which look nothing like they do in-game in SMB3 Foundry because of this issue. It's also the only way to have gaps in the ground in the desert tileset, so it's pretty important to get this one looking right.
- **Ship Object $03, $C0 (Invisible Platform)** - Again used to block out parts of other objects and make gaps. These don't even give a bounding box in SMB3 Foundry, making them all but impossible to edit/utilize.

Do not render these objects as transparent. Draw them as opaque blocks of the BG color instead. This should make their appearance match the game itself.

Edit: This problem also affects objects with transparent sections that overlap other objects. In general, it seems SMB3 Foundry incorrectly assumes the BG color is always transparent and does not render as an NES would.

**Comment by TheJoeSmo** [comment]
I agree this is a major problem with the editor at the moment.  The reason the blocks look wrong are two fold.  The most common, such as gaps and whatnot, derive from the blocks inside the generator overlapping.  And the second issue derives from 'dynamic' generators being shorthanded in the code.  To address these problems, we would need to rewrite all of the code to load the level properly as similar to the game.  That is what is trying to be achieved currently in #85.  Once we get that accepted, we can begin to modify the generators to render similar to the game.  There a few other edge cases as well, such as performance and resizing, but wanted to let you know where we are at the moment.

**Comment by mchlnix** [comment]
That's what the View -> Block transparency setting is for. Some object render correctly, with this setting on (Background Bushes in 1.1), some with this off (the gap you are describing). Most don't care, since they have no transparency, or its hardcoded in the tiles.

We could add a "needs transparency" flag to the data.dat file, but I'm not sure that's worth the effort and would hide some information.

So the first two are usable, when changing to block transparency setting, and the third does draw a bounding box. It's just, that it is not visible on the black background, since the outline is also black and the blue tint of selected objects is not visible on black.
Still a problem, but not with the object, but with the way selection is drawn.
