### ISSUE TITLE
Play level in designated world

### ISSUE THREAD

**Issue by imadethis-smb3** [mchlnix/SMB3-Foundry#92]
First of all, the "Play Level" button is awesome!  

There are a few enemies, however, that change behavior based on the world that they are in (fire piranha, boom booms, koopa kids).  It would be nice if there was a way to have "Play Level" specify the world you want to play it in so you can see how it actually plays in the world you intend it for.  Currently the "Play level" button plays the level with world 1 behavior.

I am not sure how to make this selection intuitive or if it can be automatic for levels that are placed in a world.  It's just something I noticed.  I built a level based on the world 1 behavior but it's in world 2 and I wasn't aware they would have different behavior in world 2.  Now I know... :D  The timing of all the fire piranha balls are messed up.  I'm probably going to hack it so they have the world 1 behavior in world 2, but this "difference in behavior" might trip other people up from time to time too.

I just use a debug mode to skip to the world I want and walk through levels so this isn't a big deal for me. For those that don't have that enabled, this difference in how the enemies act will be harder to debug/work with.

**Comment by TheJoeSmo** [comment]
I agree that is something overlooked inside Foundry.  A dropdown to select the world should do the trick.  And maybe an ability to change where Mario spawns on each world map, as we will have to implement that as well.

**Comment by mchlnix** [comment]
It wasn't overlooked and it isn't hard to place the level where ever you want, the difficult part was to get Mario to the world map you need to go to.

I could also move world 2 to the place of world 1 so Mario spawns there at the beginning of the game, but inside the Rom it would still be world 1 with world 2's data, so all the enemies would still behave as if they were in world 1, I'm afraid.

The key is to spawn mario in world X instead of world 1 at the start of the game, which would involve patching code in the rom.

**Comment by mchlnix** [comment]
Nevermind I got it.
